# ---------------------------------------------------------------------------------------
# ------------------------------- CLOUD BUILD CONFIG ------------------------------------
# ---------------------------------------------------------------------------------------
# The production version of these sapper apps use a multi staged docker build. Caching 
# is not automatically supported by cloud build but can be done manually, even in multi
# staged builds. Because build time currently is not an issue and the caching could
# create extra cost it is not used anymore.
# More details at https://github.com/jgero/my-webpage/issues/22
# ---------------------------------------------------------------------------------------
steps:
# ---------------------------------------------------------------------------------------
# --------------------------- BUILD AND PUSH IMAGES -------------------------------------
# ---------------------------------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'make'
  args:
    - 'push'
# ---------------------------------------------------------------------------------------
# ------------------------------- DEPLOY IMAGES -----------------------------------------
# ---------------------------------------------------------------------------------------
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'make'
  args:
    - 'deploy'
images:
- 'eu.gcr.io/webpage-jgero/portfolio-page:latest'
- 'eu.gcr.io/webpage-jgero/space-page:latest'
- 'eu.gcr.io/webpage-jgero/scavenger-hunt-page:latest'
- 'eu.gcr.io/webpage-jgero/main-page:latest'
